---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: comments-api
  template:
    metadata:
      labels:
        name: comments-api
    spec:
      containers:
        - name: application
          image: "wfen/comments-api:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              value: "$DB_USERNAME"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_PORT
              value: "$DB_PORT"
            - name: DB_TABLE
              value: "$DB_TABLE"
            - name: DB_SSLMODE
              value: "$DB_SSLMODE"
            - name: DB_SSLROOTCERT
              value: "$DB_SSLROOTCERT"
            - name: DB_OPTIONS
              value: "$DB_OPTIONS"